# Required volumes:
#    - "./frontend:/app"
#    - "./.cache/frontend/node_modules:/app/node_modules"
#    - "./.cache/frontend/dist:/app/dist"

FROM node:20-alpine3.18

WORKDIR /app

ENTRYPOINT ["/bin/sh", "-c", "npm install;npm run start-dockerdev"]

EXPOSE 4200
